/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check endpoint */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login with email and password */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get CSRF token (double-submit cookie) */
        get: operations["AuthController_getCsrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout (clear auth cookies) */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["AuthController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all stores owned by user */
        get: operations["StoresController_findAll"];
        put?: never;
        /** Create a new store */
        post: operations["StoresController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a store by ID */
        get: operations["StoresController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a store */
        patch: operations["StoresController_update"];
        trace?: never;
    };
    "/api/v1/stores/{storeId}/telegram/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connect a Telegram bot to the store */
        post: operations["TelegramController_connect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{storeId}/telegram/bot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Telegram bot status */
        get: operations["TelegramController_getBotStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/telegram/webhook/{storeId}/{secret}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Telegram webhook endpoint */
        post: operations["TelegramController_webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{storeId}/analytics/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get store dashboard analytics */
        get: operations["AnalyticsController_getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{storeId}/analytics/revenue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get revenue chart data */
        get: operations["AnalyticsController_getRevenueChart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{storeId}/analytics/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get customer growth data */
        get: operations["AnalyticsController_getCustomerGrowth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{storeId}/analytics/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get store events */
        get: operations["AnalyticsController_getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{storeId}/analytics/events/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get event counts by type */
        get: operations["AnalyticsController_getEventCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{storeId}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all categories */
        get: operations["CatalogController_getCategories"];
        put?: never;
        /** Create a category */
        post: operations["CatalogController_createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{storeId}/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a category by ID */
        get: operations["CatalogController_getCategory"];
        put?: never;
        post?: never;
        /** Delete a category */
        delete: operations["CatalogController_deleteCategory"];
        options?: never;
        head?: never;
        /** Update a category */
        patch: operations["CatalogController_updateCategory"];
        trace?: never;
    };
    "/api/v1/stores/{storeId}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all products */
        get: operations["CatalogController_getProducts"];
        put?: never;
        /** Create a product */
        post: operations["CatalogController_createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{storeId}/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a product by ID */
        get: operations["CatalogController_getProduct"];
        put?: never;
        post?: never;
        /** Delete a product */
        delete: operations["CatalogController_deleteProduct"];
        options?: never;
        head?: never;
        /** Update a product */
        patch: operations["CatalogController_updateProduct"];
        trace?: never;
    };
    "/api/v1/stores/{storeId}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all orders for a store */
        get: operations["OrdersController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{storeId}/orders/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get order statistics */
        get: operations["OrdersController_getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{storeId}/orders/{orderId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an order by ID */
        get: operations["OrdersController_findOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{storeId}/orders/{orderId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update order status */
        patch: operations["OrdersController_updateStatus"];
        trace?: never;
    };
    "/api/v1/stores/{storeId}/payments/settings/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get payment settings for a provider */
        get: operations["PaymentsController_getSettings"];
        /** Update payment settings for a provider */
        put: operations["PaymentsController_updateSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/payme/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Payme payment callback */
        post: operations["PaymentsController_paymeCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/click/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Click payment callback */
        post: operations["PaymentsController_clickCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{storeId}/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all store locations */
        get: operations["DeliveryController_getLocations"];
        put?: never;
        /** Create a store location */
        post: operations["DeliveryController_createLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{storeId}/locations/{locationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a store location */
        get: operations["DeliveryController_getLocation"];
        put?: never;
        post?: never;
        /** Delete a store location */
        delete: operations["DeliveryController_deleteLocation"];
        options?: never;
        head?: never;
        /** Update a store location */
        patch: operations["DeliveryController_updateLocation"];
        trace?: never;
    };
    "/api/v1/stores/{storeId}/delivery-zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all delivery zones */
        get: operations["DeliveryController_getZones"];
        put?: never;
        /** Create a delivery zone */
        post: operations["DeliveryController_createZone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{storeId}/delivery-zones/{zoneId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a delivery zone */
        get: operations["DeliveryController_getZone"];
        put?: never;
        post?: never;
        /** Delete a delivery zone */
        delete: operations["DeliveryController_deleteZone"];
        options?: never;
        head?: never;
        /** Update a delivery zone */
        patch: operations["DeliveryController_updateZone"];
        trace?: never;
    };
    "/api/v1/stores/{storeId}/coupons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all coupons */
        get: operations["CouponsController_findAll"];
        put?: never;
        /** Create a coupon */
        post: operations["CouponsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{storeId}/coupons/{couponId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a coupon by ID */
        get: operations["CouponsController_findOne"];
        put?: never;
        post?: never;
        /** Delete a coupon */
        delete: operations["CouponsController_delete"];
        options?: never;
        head?: never;
        /** Update a coupon */
        patch: operations["CouponsController_update"];
        trace?: never;
    };
    "/api/v1/stores/{storeId}/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all campaigns */
        get: operations["CrmController_getCampaigns"];
        put?: never;
        /** Create a campaign */
        post: operations["CrmController_createCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{storeId}/campaigns/{campaignId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a campaign */
        get: operations["CrmController_getCampaign"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{storeId}/campaigns/{campaignId}/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dispatch a campaign */
        post: operations["CrmController_dispatchCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{storeId}/segments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all segments */
        get: operations["CrmController_getSegments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stores/{storeId}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all customer tags */
        get: operations["CrmController_getTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterDto: {
            /** @example user@example.com */
            email: string;
            /** @example Password123! */
            password: string;
            /** @example John Doe */
            fullName: string;
        };
        AuthUserDto: {
            /** @example 1 */
            id: string;
            /** @example user@example.com */
            email: string;
            /** @example John Doe */
            fullName: string;
            /** @enum {string} */
            role: "ADMIN" | "SELLER";
        };
        AuthSessionDto: {
            /**
             * @description JWT access token. Also set as HttpOnly cookie "access_token" for browser clients.
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            user: components["schemas"]["AuthUserDto"];
        };
        LoginDto: {
            /** @example user@example.com */
            email: string;
            /** @example Password123! */
            password: string;
        };
        CsrfTokenDto: {
            /**
             * @description CSRF token that must be echoed in the "x-csrf-token" header for cookie-authenticated unsafe requests.
             * @example 2f6d0b3d0d3f6f4c...
             */
            csrfToken: string;
        };
        LogoutDto: {
            /** @example true */
            ok: boolean;
        };
        AuthStoreSummaryDto: {
            /** @example 10 */
            id: string;
            /** @example My Store */
            name: string;
            /** @example my-store */
            slug: string;
            /** @enum {string} */
            status: "ACTIVE" | "SUSPENDED" | "DELETED";
        };
        AuthMeDto: {
            /** @example 1 */
            id: string;
            /** @example user@example.com */
            email: string;
            /** @example John Doe */
            fullName: string;
            /** @enum {string} */
            role: "ADMIN" | "SELLER";
            /** @example true */
            isActive: boolean;
            /** Format: date-time */
            createdAt: string;
            permissions: string[];
            stores: components["schemas"]["AuthStoreSummaryDto"][];
        };
        CreateStoreDto: {
            /** @example My Store */
            name: string;
            /** @example my-store */
            slug: string;
            /** @example A great store description */
            description?: string;
            /** @example https://example.com/logo.png */
            logoUrl?: string;
            /**
             * @default [
             *       "uz",
             *       "ru"
             *     ]
             * @example [
             *       "uz",
             *       "ru"
             *     ]
             */
            supportedLanguages: string[];
            /**
             * @default uz
             * @example uz
             */
            defaultLanguage: string;
            /**
             * @default UZS
             * @example UZS
             */
            currency: string;
            /**
             * @default Asia/Tashkent
             * @example Asia/Tashkent
             */
            timezone: string;
        };
        UpdateStoreDto: {
            /** @example My Store */
            name?: string;
            /** @example my-store */
            slug?: string;
            /** @example A great store description */
            description?: string;
            /** @example https://example.com/logo.png */
            logoUrl?: string;
            /**
             * @default [
             *       "uz",
             *       "ru"
             *     ]
             * @example [
             *       "uz",
             *       "ru"
             *     ]
             */
            supportedLanguages: string[];
            /**
             * @default uz
             * @example uz
             */
            defaultLanguage: string;
            /**
             * @default UZS
             * @example UZS
             */
            currency: string;
            /**
             * @default Asia/Tashkent
             * @example Asia/Tashkent
             */
            timezone: string;
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED" | "DELETED";
        };
        ConnectTelegramDto: {
            /** @example 123456789:ABCdefGHIjklMNOpqrSTUvwxYZ */
            token: string;
            /** @example https://your-domain.com */
            webhookBaseUrl?: string;
        };
        CreateCategoryDto: {
            /** @example Electronics */
            name: string;
            /** @example Электроника */
            nameRu?: string;
            /** @example electronics */
            slug: string;
            /** @example https://example.com/image.jpg */
            imageUrl?: string;
            parentId?: string;
            /** @example 0 */
            sortOrder?: number;
            /** @example true */
            isActive?: boolean;
        };
        UpdateCategoryDto: {
            /** @example Electronics */
            name?: string;
            /** @example Электроника */
            nameRu?: string;
            /** @example electronics */
            slug?: string;
            /** @example https://example.com/image.jpg */
            imageUrl?: string;
            parentId?: string;
            /** @example 0 */
            sortOrder?: number;
            /** @example true */
            isActive?: boolean;
        };
        CreateProductDto: {
            /** @example Smartphone */
            name: string;
            /** @example A great smartphone */
            description?: string;
            /** @example 1000000 */
            price: number;
            /** @example 100 */
            stockQty?: number;
            categoryId?: string;
            /** @example 0 */
            sortOrder?: number;
            /** @example true */
            isActive?: boolean;
            /**
             * @example [
             *       "https://example.com/img1.jpg"
             *     ]
             */
            imageUrls?: string[];
        };
        UpdateProductDto: {
            /** @example Smartphone */
            name?: string;
            /** @example A great smartphone */
            description?: string;
            /** @example 1000000 */
            price?: number;
            /** @example 100 */
            stockQty?: number;
            categoryId?: string;
            /** @example 0 */
            sortOrder?: number;
            /** @example true */
            isActive?: boolean;
            /**
             * @example [
             *       "https://example.com/img1.jpg"
             *     ]
             */
            imageUrls?: string[];
        };
        UpdateOrderStatusDto: {
            /** @enum {string} */
            status: "DRAFT" | "PENDING_PAYMENT" | "PAID" | "PROCESSING" | "READY" | "SHIPPED" | "DELIVERED" | "CANCELLED" | "REFUNDED" | "PENDING" | "CONFIRMED";
            /** @example Order is being prepared */
            comment?: string;
        };
        UpdatePaymentSettingsDto: {
            /** @example true */
            isEnabled?: boolean;
            /** @example merchant_123 */
            merchantId?: string;
            /** @example secret_key_123 */
            secretKey?: string;
            config?: Record<string, never>;
        };
        CreateStoreLocationDto: {
            /** @example Main Store */
            name: string;
            /** @example Tashkent, Chilanzar 1 */
            address: string;
            /** @example 41.2995 */
            latitude?: number;
            /** @example 69.2401 */
            longitude?: number;
            /** @example +998901234567 */
            phone?: string;
            /** @example true */
            isActive?: boolean;
        };
        UpdateStoreLocationDto: {
            /** @example Main Store */
            name?: string;
            /** @example Tashkent, Chilanzar 1 */
            address?: string;
            /** @example 41.2995 */
            latitude?: number;
            /** @example 69.2401 */
            longitude?: number;
            /** @example +998901234567 */
            phone?: string;
            /** @example true */
            isActive?: boolean;
        };
        DeliveryTierDto: {
            /** @example 0 */
            minOrderAmount: number;
            /** @example 15000 */
            deliveryFee: number;
        };
        CreateDeliveryZoneDto: {
            /** @example Chilanzar District */
            name: string;
            /** @description GeoJSON polygon */
            polygon?: Record<string, never>;
            /** @example true */
            isActive?: boolean;
            tiers?: components["schemas"]["DeliveryTierDto"][];
        };
        UpdateDeliveryZoneDto: {
            /** @example Chilanzar District */
            name?: string;
            /** @description GeoJSON polygon */
            polygon?: Record<string, never>;
            /** @example true */
            isActive?: boolean;
            tiers?: components["schemas"]["DeliveryTierDto"][];
        };
        CreateCouponDto: {
            /** @example SUMMER20 */
            code: string;
            /** @enum {string} */
            type: "PERCENTAGE" | "FIXED_AMOUNT";
            /** @example 20 */
            value: number;
            /** @example 100000 */
            minOrderAmount?: number;
            /** @example 50000 */
            maxDiscount?: number;
            /** @example 100 */
            usageLimit?: number;
            /** @example 1 */
            perUserLimit?: number;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** @example true */
            isActive?: boolean;
            /** @description Product IDs */
            productIds?: string[];
            /** @description Category IDs */
            categoryIds?: string[];
        };
        UpdateCouponDto: {
            /** @example SUMMER20 */
            code?: string;
            /** @enum {string} */
            type?: "PERCENTAGE" | "FIXED_AMOUNT";
            /** @example 20 */
            value?: number;
            /** @example 100000 */
            minOrderAmount?: number;
            /** @example 50000 */
            maxDiscount?: number;
            /** @example 100 */
            usageLimit?: number;
            /** @example 1 */
            perUserLimit?: number;
            /** Format: date-time */
            startsAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            /** @example true */
            isActive?: boolean;
            /** @description Product IDs */
            productIds?: string[];
            /** @description Category IDs */
            categoryIds?: string[];
        };
        CreateCampaignDto: {
            /** @example Summer Sale Announcement */
            name: string;
            /** @example Get 20% off on all products! */
            message: string;
            /** @example https://example.com/image.jpg */
            imageUrl?: string;
            segmentId?: string;
            /** Format: date-time */
            scheduledAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Service is unhealthy */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionDto"];
                };
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionDto"];
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getCsrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfTokenDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutDto"];
                };
            };
        };
    };
    AuthController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StoresController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of stores */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StoresController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStoreDto"];
            };
        };
        responses: {
            /** @description Store created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Store slug already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StoresController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Store details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Store not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StoresController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStoreDto"];
            };
        };
        responses: {
            /** @description Store updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden - not owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Store not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TelegramController_connect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectTelegramDto"];
            };
        };
        responses: {
            /** @description Bot connected successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid bot token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TelegramController_getBotStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bot status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bot not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TelegramController_webhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                secret: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Update processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnalyticsController_getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Store ID */
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnalyticsController_getRevenueChart: {
        parameters: {
            query?: {
                /** @description Number of days to include */
                days?: number;
            };
            header?: never;
            path: {
                /** @description Store ID */
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnalyticsController_getCustomerGrowth: {
        parameters: {
            query?: {
                /** @description Number of days to include */
                days?: number;
            };
            header?: never;
            path: {
                /** @description Store ID */
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnalyticsController_getEvents: {
        parameters: {
            query?: {
                /** @description Page number */
                page?: number;
                /** @description Items per page */
                limit?: number;
                /** @description Filter by event name */
                eventName?: string;
            };
            header?: never;
            path: {
                /** @description Store ID */
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AnalyticsController_getEventCounts: {
        parameters: {
            query?: {
                /** @description Number of days to include */
                days?: number;
            };
            header?: never;
            path: {
                /** @description Store ID */
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogController_getCategories: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogController_createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            /** @description Category created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogController_getCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogController_deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Category deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogController_updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            /** @description Category updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogController_getProducts: {
        parameters: {
            query?: {
                categoryId?: string;
                isActive?: boolean;
            };
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogController_createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            /** @description Product created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogController_getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogController_deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CatalogController_updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            /** @description Product updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_findAll: {
        parameters: {
            query?: {
                status?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_getStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                orderId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Order details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OrdersController_updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                orderId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderStatusDto"];
            };
        };
        responses: {
            /** @description Order status updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Payment settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePaymentSettingsDto"];
            };
        };
        responses: {
            /** @description Payment settings updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_paymeCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Callback processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_clickCallback: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Callback processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeliveryController_getLocations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of locations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeliveryController_createLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStoreLocationDto"];
            };
        };
        responses: {
            /** @description Location created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeliveryController_getLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                locationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Location details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeliveryController_deleteLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                locationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Location deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeliveryController_updateLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                locationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStoreLocationDto"];
            };
        };
        responses: {
            /** @description Location updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeliveryController_getZones: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of zones */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeliveryController_createZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDeliveryZoneDto"];
            };
        };
        responses: {
            /** @description Zone created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeliveryController_getZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                zoneId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Zone details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeliveryController_deleteZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                zoneId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Zone deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeliveryController_updateZone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                zoneId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDeliveryZoneDto"];
            };
        };
        responses: {
            /** @description Zone updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CouponsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of coupons */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CouponsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCouponDto"];
            };
        };
        responses: {
            /** @description Coupon created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CouponsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                couponId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Coupon details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CouponsController_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                couponId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Coupon deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CouponsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                couponId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCouponDto"];
            };
        };
        responses: {
            /** @description Coupon updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CrmController_getCampaigns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of campaigns */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CrmController_createCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCampaignDto"];
            };
        };
        responses: {
            /** @description Campaign created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CrmController_getCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                campaignId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CrmController_dispatchCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
                campaignId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaign dispatched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CrmController_getSegments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of segments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CrmController_getTags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                storeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
